export interface MangaSeries {
  id: number
  title: string
  slug: string
  author: string
  artist?: string
  rating: number
  ratingCount: number
  genre: string
  status: "Ongoing" | "Completed" | "Hiatus"
  chapters: number
  latestChapter: string
  description: string
  coverUrl: string
  views: string
  updatedAt: string
  tags: string[]
}

export const mangaData: MangaSeries[] = [
  {
    id: 1,
    title: "Solo Leveling",
    slug: "solo-leveling",
    author: "Chugong",
    artist: "Dubu",
    rating: 4.8,
    ratingCount: 12453,
    genre: "Action",
    status: "Completed",
    chapters: 179,
    latestChapter: "Ch. 179",
    description: "In a world where hunters must battle deadly monsters, Sung Jin-Woo finds himself as the weakest of all...",
    coverUrl: "/placeholder.svg?height=400&width=280",
    views: "2.1M",
    updatedAt: "2 hours ago",
    tags: ["Fantasy", "Action", "Adventure"],
  },
  {
    id: 2,
    title: "One Piece",
    slug: "one-piece",
    author: "Eiichiro Oda",
    rating: 4.9,
    ratingCount: 45210,
    genre: "Adventure",
    status: "Ongoing",
    chapters: 1120,
    latestChapter: "Ch. 1120",
    description: "Monkey D. Luffy sets out on a journey to find the legendary treasure One Piece...",
    coverUrl: "/placeholder.svg?height=400&width=280",
    views: "5.8M",
    updatedAt: "5 days ago",
    tags: ["Shonen", "Adventure", "Comedy"],
  },
  {
    id: 3,
    title: "Jujutsu Kaisen",
    slug: "jujutsu-kaisen",
    author: "Gege Akutami",
    rating: 4.7,
    ratingCount: 18934,
    genre: "Supernatural",
    status: "Completed",
    chapters: 271,
    latestChapter: "Ch. 271",
    description: "A boy swallows a cursed talisman and becomes host to a powerful curse...",
    coverUrl: "/placeholder.svg?height=400&width=280",
    views: "3.4M",
    updatedAt: "1 month ago",
    tags: ["Supernatural", "Action", "Dark Fantasy"],
  },
  {
    id: 4,
    title: "Chainsaw Man",
    slug: "chainsaw-man",
    author: "Tatsuki Fujimoto",
    rating: 4.6,
    ratingCount: 15678,
    genre: "Horror",
    status: "Ongoing",
    chapters: 185,
    latestChapter: "Ch. 185",
    description: "Denji is a teenage boy living with a Chainsaw Devil named Pochita...",
    coverUrl: "/placeholder.svg?height=400&width=280",
    views: "2.8M",
    updatedAt: "3 days ago",
    tags: ["Horror", "Action", "Dark"],
  },
  {
    id: 5,
    title: "Spy x Family",
    slug: "spy-x-family",
    author: "Tatsuya Endo",
    rating: 4.7,
    ratingCount: 22345,
    genre: "Comedy",
    status: "Ongoing",
    chapters: 107,
    latestChapter: "Ch. 107",
    description: "A spy must build a fake family to execute a mission, not realizing that his adopted daughter is a telepath...",
    coverUrl: "/placeholder.svg?height=400&width=280",
    views: "4.1M",
    updatedAt: "1 week ago",
    tags: ["Comedy", "Action", "Slice of Life"],
  },
  {
    id: 6,
    title: "Blue Lock",
    slug: "blue-lock",
    author: "Muneyuki Kaneshiro",
    artist: "Yusuke Nomura",
    rating: 4.5,
    ratingCount: 9876,
    genre: "Sports",
    status: "Ongoing",
    chapters: 280,
    latestChapter: "Ch. 280",
    description: "After a devastating loss in the 2018 World Cup, Japan decides to create a striker who can lead them to victory...",
    coverUrl: "/placeholder.svg?height=400&width=280",
    views: "1.9M",
    updatedAt: "4 days ago",
    tags: ["Sports", "Drama", "Psychological"],
  },
  {
    id: 7,
    title: "Demon Slayer",
    slug: "demon-slayer",
    author: "Koyoharu Gotouge",
    rating: 4.8,
    ratingCount: 34567,
    genre: "Action",
    status: "Completed",
    chapters: 205,
    latestChapter: "Ch. 205",
    description: "Tanjiro sets out to become a demon slayer to avenge his family and cure his sister...",
    coverUrl: "/placeholder.svg?height=400&width=280",
    views: "4.5M",
    updatedAt: "2 years ago",
    tags: ["Action", "Supernatural", "Historical"],
  },
  {
    id: 8,
    title: "My Hero Academia",
    slug: "my-hero-academia",
    author: "Kohei Horikoshi",
    rating: 4.4,
    ratingCount: 28901,
    genre: "Superhero",
    status: "Completed",
    chapters: 430,
    latestChapter: "Ch. 430",
    description: "In a world where nearly everyone has superpowers, a boy without them still dreams of becoming a hero...",
    coverUrl: "/placeholder.svg?height=400&width=280",
    views: "3.9M",
    updatedAt: "6 months ago",
    tags: ["Superhero", "Action", "School"],
  },
  {
    id: 9,
    title: "Attack on Titan",
    slug: "attack-on-titan",
    author: "Hajime Isayama",
    rating: 4.9,
    ratingCount: 41234,
    genre: "Dark Fantasy",
    status: "Completed",
    chapters: 139,
    latestChapter: "Ch. 139",
    description: "Humanity lives within enormous walled cities to protect themselves from Titans...",
    coverUrl: "/placeholder.svg?height=400&width=280",
    views: "5.2M",
    updatedAt: "3 years ago",
    tags: ["Dark Fantasy", "Action", "Military"],
  },
  {
    id: 10,
    title: "Tokyo Revengers",
    slug: "tokyo-revengers",
    author: "Ken Wakui",
    rating: 4.3,
    ratingCount: 11234,
    genre: "Drama",
    status: "Completed",
    chapters: 278,
    latestChapter: "Ch. 278",
    description: "Takemichi travels back in time to save his girlfriend from a gang conflict...",
    coverUrl: "/placeholder.svg?height=400&width=280",
    views: "2.3M",
    updatedAt: "1 year ago",
    tags: ["Drama", "Action", "Time Travel"],
  },
  {
    id: 11,
    title: "Vinland Saga",
    slug: "vinland-saga",
    author: "Makoto Yukimura",
    rating: 4.8,
    ratingCount: 8765,
    genre: "Historical",
    status: "Completed",
    chapters: 209,
    latestChapter: "Ch. 209",
    description: "Thorfinn pursues a journey of exploration and redemption in the Viking age...",
    coverUrl: "/placeholder.svg?height=400&width=280",
    views: "1.5M",
    updatedAt: "8 months ago",
    tags: ["Historical", "Action", "Drama"],
  },
  {
    id: 12,
    title: "Kaiju No. 8",
    slug: "kaiju-no-8",
    author: "Naoya Matsumoto",
    rating: 4.5,
    ratingCount: 7654,
    genre: "Sci-Fi",
    status: "Ongoing",
    chapters: 115,
    latestChapter: "Ch. 115",
    description: "Kafka Hibino gains the power to transform into a kaiju while fighting to protect Japan...",
    coverUrl: "/placeholder.svg?height=400&width=280",
    views: "1.8M",
    updatedAt: "1 week ago",
    tags: ["Sci-Fi", "Action", "Monster"],
  },
  {
    id: 13,
    title: "Dandadan",
    slug: "dandadan",
    author: "Yukinobu Tatsu",
    rating: 4.6,
    ratingCount: 6543,
    genre: "Supernatural",
    status: "Ongoing",
    chapters: 180,
    latestChapter: "Ch. 180",
    description: "A supernatural battle manga combining aliens and ghosts with teenage drama...",
    coverUrl: "/placeholder.svg?height=400&width=280",
    views: "1.4M",
    updatedAt: "2 days ago",
    tags: ["Supernatural", "Comedy", "Sci-Fi"],
  },
  {
    id: 14,
    title: "Berserk",
    slug: "berserk",
    author: "Kentaro Miura",
    rating: 4.9,
    ratingCount: 38901,
    genre: "Dark Fantasy",
    status: "Ongoing",
    chapters: 376,
    latestChapter: "Ch. 376",
    description: "Guts, a lone mercenary, battles his way through a world of demons and darkness...",
    coverUrl: "/placeholder.svg?height=400&width=280",
    views: "3.7M",
    updatedAt: "3 months ago",
    tags: ["Dark Fantasy", "Horror", "Action"],
  },
  {
    id: 15,
    title: "Naruto",
    slug: "naruto",
    author: "Masashi Kishimoto",
    rating: 4.7,
    ratingCount: 52345,
    genre: "Action",
    status: "Completed",
    chapters: 700,
    latestChapter: "Ch. 700",
    description: "Naruto Uzumaki dreams of becoming the strongest ninja and leader of his village...",
    coverUrl: "/placeholder.svg?height=400&width=280",
    views: "6.1M",
    updatedAt: "10 years ago",
    tags: ["Action", "Adventure", "Ninja"],
  },
  {
    id: 16,
    title: "Mashle",
    slug: "mashle",
    author: "Hajime Komoto",
    rating: 4.4,
    ratingCount: 5432,
    genre: "Comedy",
    status: "Completed",
    chapters: 162,
    latestChapter: "Ch. 162",
    description: "In a magical world, Mash uses nothing but muscle power to survive...",
    coverUrl: "/placeholder.svg?height=400&width=280",
    views: "1.1M",
    updatedAt: "6 months ago",
    tags: ["Comedy", "Action", "Fantasy"],
  },
  {
    id: 17,
    title: "Oshi no Ko",
    slug: "oshi-no-ko",
    author: "Aka Akasaka",
    artist: "Mengo Yokoyari",
    rating: 4.6,
    ratingCount: 14567,
    genre: "Drama",
    status: "Completed",
    chapters: 166,
    latestChapter: "Ch. 166",
    description: "A doctor reincarnates as the child of his favorite idol, uncovering the dark side of entertainment...",
    coverUrl: "/placeholder.svg?height=400&width=280",
    views: "2.5M",
    updatedAt: "4 months ago",
    tags: ["Drama", "Mystery", "Psychological"],
  },
  {
    id: 18,
    title: "Sakamoto Days",
    slug: "sakamoto-days",
    author: "Yuto Suzuki",
    rating: 4.5,
    ratingCount: 8901,
    genre: "Action",
    status: "Ongoing",
    chapters: 195,
    latestChapter: "Ch. 195",
    description: "A retired legendary hitman now runs a convenience store but trouble keeps finding him...",
    coverUrl: "/placeholder.svg?height=400&width=280",
    views: "1.6M",
    updatedAt: "5 days ago",
    tags: ["Action", "Comedy", "Thriller"],
  },
  {
    id: 19,
    title: "Hunter x Hunter",
    slug: "hunter-x-hunter",
    author: "Yoshihiro Togashi",
    rating: 4.9,
    ratingCount: 36789,
    genre: "Adventure",
    status: "Hiatus",
    chapters: 400,
    latestChapter: "Ch. 400",
    description: "Gon Freecss sets out to become a Hunter and find his father...",
    coverUrl: "/placeholder.svg?height=400&width=280",
    views: "4.3M",
    updatedAt: "2 months ago",
    tags: ["Adventure", "Action", "Fantasy"],
  },
  {
    id: 20,
    title: "Black Clover",
    slug: "black-clover",
    author: "Yuki Tabata",
    rating: 4.4,
    ratingCount: 19234,
    genre: "Fantasy",
    status: "Ongoing",
    chapters: 374,
    latestChapter: "Ch. 374",
    description: "In a world of magic, Asta is born without any magical power and aims to become the Wizard King...",
    coverUrl: "/placeholder.svg?height=400&width=280",
    views: "3.2M",
    updatedAt: "1 week ago",
    tags: ["Fantasy", "Action", "Shonen"],
  },
]
